id: organism_taxon
schema_generating: true
description: 'A classification of a set of organisms. Examples: NCBITaxon:9606 (Homo
  sapiens), NCBITaxon:2 (Bacteria). Can also be used to represent strains or subspecies.'
display_name: organism taxon
document_category: organism taxon
weight: 20
fields:
- id: id
  description: A unique identifier for a resource. Must be either a CURIE shorthand
    for a URI or a complete URI
  display_name: id
- id: iri
  description: An IRI for an entity. This is determined by the id using expansion
    rules.
  display_name: iri
- id: type
  display_name: type
- id: name
  description: A human-readable name for a thing
  display_name: name
- id: description
  description: a human-readable description of a thing
  display_name: description
- id: source
  description: a lightweight analog to the association class 'has provider' slot,
    which is the string name, or the authoritative (i.e. database) namespace, designating
    the origin of the entity to which the slot belongs.
  display_name: source
- id: provided_by
  description: connects an association to the agent (person, organization or group)
    that provided it
  display_name: provided by
  cardinality: multi
- id: has_attribute
  description: connects any named thing to an attribute
  display_name: has attribute
  cardinality: multi
- id: category
  display_name: named thing_category
  cardinality: multi
