id: severity_value
schema_generating: true
description: describes the severity of a phenotypic feature or disease
display_name: severity value
document_category: severity value
weight: 20
fields:
- id: has_attribute_type
  description: connects an attribute to a class that describes it
  display_name: has attribute type
- id: has_quantitative_value
  description: connects an attribute to a value
  display_name: has quantitative value
  cardinality: multi
- id: has_qualitative_value
  description: connects an attribute to a value
  display_name: has qualitative value
